### ISSUE TITLE
What changes needed to adapt this app to aurelia js

### ISSUE THREAD

**Issue by khuzemakanore** [Breeze/northwind-demo#11]
I need to use Aurelia JS as client framework what are the changes I need to make for it to work.

**Comment by steveschmitt** [comment]
Good question!  We should make an Aurelia demo as well.

**Comment by WisdomCorp** [comment]
That would be great please. 
I have successfully done the Asp.Net Core 3.1 walkthrough.
And I have successfully followed Angular Walkthrough for Aurelia 1 up-to generate-entities.js. After that I am lost :)
I will gladly help anyway I could. Thanks

**Comment by steveschmitt** [comment]
Have you seen https://github.com/jdanyow/aurelia-breeze and https://github.com/jdanyow/aurelia-breeze-northwind ?  They are old repositories and use old versions of Aurelia and Breeze, but they may be helpful in getting started.

**Comment by WisdomCorp** [comment]
I have used that. But I need to work on .Net Core with Breeze JS .Net core. As you already have other walkthrough, It will help Aurelia JS community

**Comment by WisdomCorp** [comment]
any update on this one :)

**Comment by steveschmitt** [comment]
Thanks for your patience.  I've finally added an Aurelia demo.  See [STEPS-Client-Aurelia](https://github.com/Breeze/northwind-demo/blob/master/client/STEPS-Client-Aurelia.md) and the [northwind-aurelia](https://github.com/Breeze/northwind-demo/tree/master/client/northwind-aurelia) directory.  

The demo uses [Aurelia 2](https://github.com/aurelia/aurelia), whose [docs](https://docs.aurelia.io/) are still incomplete.  No aurelia-breeze adapter was required - it just works!

BTW, the .NET 5 demo is also available in the [server](https://github.com/Breeze/northwind-demo/tree/master/server) folder.
