### ISSUE TITLE
Generate entities from metadata - ReferenceError: globalThis is not defined

### ISSUE THREAD

**Issue by KannanRams** [Breeze/northwind-demo#2]
Generate entities from metadata
While trying to run node generate-entities.js

node_modules\breeze-client\bundles\breeze-client.umd.js:2670
    globalThis['x'] = core.objectForEach(Validator, function (key, value) {
    ^

ReferenceError: globalThis is not defined
    at node_modules\breeze-client\bundles\breeze-client.umd.js:2670:5

Thanks for your assistance.

**Comment by KannanRams** [comment]
adding globalThis = this;
solved the issue;

globalThis = this;
const tsGen = require('breeze-entity-generator/tsgen-core');
const fs = require('fs');
const dir = './src/app/model';

**Comment by steveschmitt** [comment]
FYI I just published `breeze-client@2.0.0-alpha.16`, which removes the dependency on `globalThis`

Breeze doesn't _use_ a global object, but without it, some JavaScript optimizers (e.g. Terser) want to remove some internal breeze code because it has no side effects.
