### ISSUE TITLE
IdentityServer - Token Attach in breeze requests

### ISSUE THREAD

**Issue by KannanRams** [Breeze/northwind-demo#3]
Hi,
Would you provide an example for including IdentityServer token authentication in breeze requests from angular.

Thanks
Kannan

**Comment by fayeeg** [comment]
Hello Breeze Team

Any advise on this issue?

**Comment by KannanRams** [comment]
Need to add token in http-interceptor

**Comment by steveschmitt** [comment]
You need to get the token from the server, store it somehow, and send it in each request via a `HttpInterceptor` . There's a brief discussion here:
https://medium.com/@ryanchenkie_40935/angular-authentication-using-the-http-client-and-http-interceptors-2f9d1540eb8
and another here:
https://itnext.io/how-to-send-jwt-automatically-in-angular-http-requests-31c1fd060871

There's nothing special about Breeze in this case; a Breeze request is like any other.  
I don't want to add token authentication to this demo, because I'm trying to keep it simple.

**Comment by steveschmitt** [comment]
@KannanRams Were you able to make progress?

**Comment by jj30** [comment]
I am having the same problem, but in React TS. I attached a bearer token to the header in both my entity-manager-provider.ts (just like the Northwind example) and the adapter.ajax.fetch.d.ts.

When I look at Fiddler (yes, some people still use Fiddler) I can't see any authorization headers present, though I get a 200 ok code.

I've been at it for about a day or so, and I know I need assistance, if you have any.

**Comment by steveschmitt** [comment]
@jj30 Can you share the code that you used to add the header?

**Comment by jj30** [comment]
In entity-manager-provider.ts


```
constructor() {
    // configure breeze adapters
    ModelLibraryBackingStoreAdapter.register();
    UriBuilderJsonAdapter.register();
    let adapterInstance = AjaxFetchAdapter.register();
    adapterInstance.defaultSettings =  { 
        headers: {
            'Authorization': 'Bearer *** removed ***',
            'Content-Type': 'application/x-www-form-urlencoded',
            'Access-Control-Allow-Origin': 'http://localhost:44362/'
        } 
    };
    let dataServiceInstance = DataServiceWebApiAdapter.register();
    NamingConvention.none.setAsDefault();
```

... (rest is as in [your documentation for creating the EntityManagerProvider](https://github.com/Breeze/northwind-core-ng-demo/blob/master/STEPS-Client-React.md))

My adapt-ajax-fetch.d.ts looks like so:

```
import * as breeze from 'breeze-client';
/** Breeze AJAX adapter using fetch API
 * See https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch
*/
 
export declare class AjaxFetchAdapter implements breeze.AjaxAdapter {
    static adapterName: string;
    name: string;
    defaultSettings: {
        headers?: any;
    };
    requestInterceptor?: (() => breeze.ChangeRequestInterceptor) | breeze.ChangeRequestInterceptor;
    
    constructor() {
        this.defaultSettings.headers = { 
            'Authorization': 'Bearer *** removed ***',
                'Content-Type': 'application/x-www-form-urlencoded',
                'Access-Control-Allow-Origin': 'http://localhost:80/'
            };
    };

    static register(config?: breeze.BreezeConfig): AjaxFetchAdapter;
    initialize(): void;
    ajax(config: breeze.AjaxConfig): void;
}

```

I don't know what I'm missing here. Do I need to implement a request interceptor?

**Comment by jj30** [comment]
![image](https://user-images.githubusercontent.com/1274227/75893315-76ca0100-5de7-11ea-98df-9f23393efb95.png)

The headers are making it into the Ajax Implementation for the metadata call.

**Comment by jj30** [comment]
Hm, ok. I think I need to have this.metadataStore.hasMetadataFor(dataService.serviceName)) == true or I need to focus on the fetchMetadata function. In our AngularJS app, the metadata call to the API doesn't need credentials and happens before logging in. So now I have a direction.

**Comment by jj30** [comment]
If I generate the metadata manually and set hasServerMetadata: false, the same thing happens with the data query. 

It's probably CORS.

**Comment by jj30** [comment]
Yep, it's CORS, because --disable-web-security in the command line of chrome works.

Man, I really hate CORS. It seems like no matter how long I've been doing this, CORS is always a huge speed bump.
