### ISSUE TITLE
Multipart Key Error

### ISSUE THREAD

**Issue by anubisatari** [Breeze/northwind-demo#32]
Hello,
I hope you are all well. I'm having this issue in an Angular application. On the server side there is no such error on the same table, however I receive the error on the Angular side of the house.  I'm using Angular 17.0.1 with a Postgres v17 database. Here is the error and the code snippet generating the error message:
Error: Ids can not be autogenerated for entities with multipart keys
    at KeyGenerator.generateTempKeyValue (breeze-client.js:10184:19)
    at EntityManager.generateTempKeyValue (breeze-client.js:11804:46)
    at checkEntityKey (breeze-client.js:12595:16)
    at breeze-client.js:11347:17
    at Object.using (breeze-client.js:600:16)
    at EntityManager.attachEntity (breeze-client.js:11345:14)
    at EntityManager.createEntity (breeze-client.js:11032:27)
    at Object.<anonymous> (alert-console.service.ts:104:8)
    at Generator.next (<anonymous>)

Code:
const newAlarmHistory: Bluealarmhistory = this.AlertSvc.AlarmHistoryDC.HistoryQuerySvc.Manager
	.createEntity(Bluealarmhistory.prototype.entityType, alarmHistory) as Bluealarmhistory;

Any guidance you can provide is greatly appreciated.

**Comment by steveschmitt** [comment]
Apparently the `Bluealarmhistory` entity type has a multipart key -- a key made up of two or more fields, which often are foreign keys.  You will need to set the values for the key fields as part of the initial values that you pass to the `createEntity` function:
```ts
const alarmHistoryValues = {
    fooId: 10,
    barId: 20,
    name: "Example",
    // other fields to set...
};

const newAlarmHistory: Bluealarmhistory = this.AlertSvc.AlarmHistoryDC.HistoryQuerySvc.Manager
.createEntity(Bluealarmhistory.prototype.entityType, alarmHistoryValues) as Bluealarmhistory;
```

**Comment by anubisatari** [comment]
I hate it when I don't give enough information.
The field in question is the id field. It is an auto increment field. Normally, I don't set a value for this field as the database handles that. In this table, the primary key consists of 3 fields, 1 of which is the auto incrementing id field. When records are added to this table on server side using the PersistenceManager, it has no problems inserting the new record.
The error only happens on the client side. In the past, I would fix this by giving the id field a value of -1 and let the backend perform identity fixup. I tried that in this case and it removed the record from the source table and did not add the record to the history table. Is there a setting or override that will allow the auto increment to work when the record is added from the client side?

**Comment by steveschmitt** [comment]
I would question why you have a 3-part key when you've got an auto-incrementing id field.  Why don't you just have the id field be the key, and have a unique index on the other two fields?

> I tried that in this case and it removed the record from the source table

I'm not sure I understand what is happening here.  I thought you were adding a new record.

> Is there a setting or override that will allow the auto increment to work when the record is added from the client side?

I don't know about that.  I'll ask @jtraband

**Comment by anubisatari** [comment]
This is time driven data and the database extension requires the partitioning fields to be part of the key. The conversation shows one is never too old to have a brain cramp. I will reduce the key to the other 2 fields and remove the auto increment field. I'm sorry to waste your time and will close this now.
I very much appreciate the work you folks have done on this library. It's the backbone of every data driven app I create.

**Comment by steveschmitt** [comment]
Thank you for your kind words. 

If it turns out that you really need that additional Id field, you could make it a Guid.  Then you can create the id when you create the entity on the client, without using autoincrement.  Seems like we are doing a lot more apps with Guids these days.

**Comment by anubisatari** [comment]
I have moved to GUIDs for some tables. After the brain cramp, the table can live without the id field. I just moved over to TimescaleDB for this particular database and need to change my thinking a little bit.
