### ISSUE TITLE
asp.net core v3.0 errors

### ISSUE THREAD

**Issue by AndreyNikiforov** [Breeze/northwind-demo#4]
Thanks for demo project!

I tried to convert it to core v3.0 and getting the following error:

> Exception thrown: 'System.MissingMethodException' in Breeze.Persistence.EFCore.dll
An unhandled exception of type 'System.MissingMethodException' occurred in Breeze.Persistence.EFCore.dll
Method not found: 'System.Type Microsoft.EntityFrameworkCore.Metadata.IProperty.get_ClrType()'.

Suspect that Breeze itself needs adjustments to support Core 3.0.

Any guidance would be appreciated.

**Comment by steveschmitt** [comment]
We are working on the Core 3 support now.

**Comment by steveschmitt** [comment]
Please see the [NorthwindCore3](https://github.com/Breeze/northwind-core-ng-demo/tree/master/NorthwindCore/NorthwindCore3) solution and let us know if it works for you.  Thanks!
