### ISSUE TITLE
where predicate with navigationproperty

### ISSUE THREAD

**Issue by roydec** [Breeze/northwind-demo#7]
When using where or select on navigationproperties breeze server errors with

> "Unable to locate property '**languageId**' on type 'System.Collections.Generic.ICollection`1[Urflex.Webshop.Model.HoseMaterialTranslation]'.",

`{"toType":"HoseMaterial:#Urflex.Webshop.Model","where":{"translations.languageId":"nl"},"orderBy":["adminTitle"],"expand":["translations"]}`

Whereas below works just fine.
`{"toType":"HoseMaterial:#Urflex.Webshop.Model","orderBy":["adminTitle"],"expand":["translations"]}`

> 
> {
>   "$id": "3",
>   "$type": "Breeze.Core.QueryResult, Breeze.Core",
>   "Results": [
>     {
>       "$id": "4",
>       "$type": "Urflex.Webshop.Model.HoseMaterial, Urflex.Webshop.Model",
>       "id": 2,
>       "adminTitle": "Braided",
>       "image": null,
>       "weight": 7.0,
>       "translations": [
>         {
>           "$id": "5",
>           "$type": "Urflex.Webshop.Model.HoseMaterialTranslation, Urflex.Webshop.Model",
>           "hoseMaterialId": 2,
>           "languageId": "nl",
>           "title": "Gebreid",
>           "description": "NL omschrijving gebreid",
>           "hoseMaterial": {
>             "$ref": "4"
>           }
>         }
>       ],
>       "hoseProductCompositions": null,
>       "hoseLengthRestraints": [],
>       "hoseMaterialPrices": null
>     },
>     {
>       "$id": "6",
>       "$type": "Urflex.Webshop.Model.HoseMaterial, Urflex.Webshop.Model",
>       "id": 1,
>       "adminTitle": "Rubber",
>       "image": null,
>       "weight": 5.0,
>       "translations": [
>         {
>           "$id": "7",
>           "$type": "Urflex.Webshop.Model.HoseMaterialTranslation, Urflex.Webshop.Model",
>           "hoseMaterialId": 1,
>           "languageId": "nl",
>           "title": "Rubber",
>           "description": "NL omschrijving Rubber",
>           "hoseMaterial": {
>             "$ref": "6"
>           }
>         }
>       ],
>       "hoseProductCompositions": null,
>       "hoseLengthRestraints": [],
>       "hoseMaterialPrices": null
>     }
>   ],
>   "InlineCount": null
> }

**Comment by steveschmitt** [comment]
While `languageId` is a property of **HoseMaterialTranslation**, it is _not_ a property of **ICollection&lt;&gt;**; that's what the error is saying.

Since **translations** is a collection, you will need to express your **where** clause as an **any** or **all** query: 
```
"where":{"translations": { "any": {"languageId":"nl"}}}
```
which means, "where any of the HoseMaterial's translations have languageId == 'nl'"

**Comment by roydec** [comment]
Tx for clarifying. As the docs of Breeze state! Feel bit embarrassed! Love Breeze btw!
