### ISSUE TITLE
error while generating metadata for .NET Core 2.2

### ISSUE THREAD

**Issue by sskasim** [Breeze/northwind-demo#8]
I am getting the following error when generating the metadata.json 

Unhandled Exception: System.InvalidOperationException: The indexes {'ProjectId', 'Title', 'DisciplineId'} on 'Deliverable' and {'ProjectId', 'DisciplineId', 'Title'} on 'Deliverable' are both mapped to 'EARNEST.Deliverable.AKDeliverableTitle' but with different columns ({'ProjectId', 'Title', 'DisciplineId'} and {'ProjectId', 'DisciplineId', 'Title'}).

I have a Deliverable table that has a Title column and two FKs ProjectId and DisciplineId from the Project and Discipline tables.
All these three columns are part of the alternate key of the Deliverable table and so part of the unique index 'EARNEST.Deliverable.AKDeliverableTitle'. Besides this the two FKs also have the individual non-unique indexes on them.

**Comment by steveschmitt** [comment]
Hmm.  EF seems to think that you have two indexes with same fields, but in a different order.  Where is the index defined?

**Comment by steveschmitt** [comment]
Were you ever able to resolve this?

**Comment by sskasim** [comment]
Nope. I did not try after that since this was an existing database and my goal then was to develop a breze sample with .NET Core for a new project I was starting. Luckily I was able to proceed with the new database without any issues. However, in future if I did upgrade that project from ASP.NET to .NET COre then I might run into this issue again or may be not.

**Comment by sskasim** [comment]
@steveschmitt I usually work on Angular apps involving complex RDBMS databases and breeze has worked quiet well for me so far. But I wonder if I am the only one using breeze today and if it is the right thing to do?

**Comment by steveschmitt** [comment]
We (IdeaBlade) are still developing Angular apps with Breeze, and are not stopping.  We still think it is the best tool for the job when relational databases are involved.

Breeze has not been marketed well (our fault) and it doesn't have the big names behind it like GraphQL does.  But in a way, GraphQL has validated our approach.  We always said that REST is a poor idiom for handling relational data, and _finally_ people agree with us.

We still think that Breeze is superior to GraphQL (and everything else) because it models relational data better.  Please help spread the word!

**Comment by sskasim** [comment]
Good to know, thanks. We have another big project by another team using GraphQL with React, and I can tell you the amount of server side code they are writing (without any reduction in the client side code) is mind blowing. when compared to what I write.

The one concern I have with breeze is if it will keep up with any breaking changes in its dependencies like .NET Core versions and Angular version. So far so good though.

**Comment by steveschmitt** [comment]
We were a bit slow getting the .NET 5 code out, but it's there now, and we'll try to keep up with Microsoft going forward.

Thanks for using Breeze!

**Comment by jtraband** [comment]
and now .NET 6 code is out as well

**Comment by sskasim** [comment]
Great! Thanks to all at IdeaBlade
